# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatbot_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63hatbot_service.proto\x12\nchatbot.v1\"\"\n\x0fQuestionRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x0e\x41nswerResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2Z\n\x0b\x43hatService\x12K\n\x0e\x41nswerGenerate\x12\x1b.chatbot.v1.QuestionRequest\x1a\x1a.chatbot.v1.AnswerResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatbot_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QUESTIONREQUEST']._serialized_start=37
  _globals['_QUESTIONREQUEST']._serialized_end=71
  _globals['_ANSWERRESPONSE']._serialized_start=73
  _globals['_ANSWERRESPONSE']._serialized_end=106
  _globals['_CHATSERVICE']._serialized_start=108
  _globals['_CHATSERVICE']._serialized_end=198
# @@protoc_insertion_point(module_scope)
