# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chatbot_service_pb2 as chatbot__service__pb2


class ChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnswerGenerate = channel.unary_unary(
                '/chatbot.v1.ChatService/AnswerGenerate',
                request_serializer=chatbot__service__pb2.QuestionRequest.SerializeToString,
                response_deserializer=chatbot__service__pb2.AnswerResponse.FromString,
                )


class ChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnswerGenerate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnswerGenerate': grpc.unary_unary_rpc_method_handler(
                    servicer.AnswerGenerate,
                    request_deserializer=chatbot__service__pb2.QuestionRequest.FromString,
                    response_serializer=chatbot__service__pb2.AnswerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chatbot.v1.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnswerGenerate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chatbot.v1.ChatService/AnswerGenerate',
            chatbot__service__pb2.QuestionRequest.SerializeToString,
            chatbot__service__pb2.AnswerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
